import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "What Is Brand Voice? (And How to Build One That Sounds Like You) — Claro",
  description: "Brand voice is what makes your copy sound like a person instead of a template. Here's how to define yours — and apply it consistently across your Etsy shop.",
  openGraph: {
    title: "What Is Brand Voice? (And How to Build One That Sounds Like You)",
    description: "Brand voice is what makes your copy sound like a person instead of a template. Here's how to define yours — and apply it consistently.",
    type: "article",
  },
};

const faqs = [
  {
    q: "What is brand voice?",
    a: "Brand voice is the consistent personality and tone of how your business communicates — across listings, social captions, emails, and message responses. It&rsquo;s not what you say. It&rsquo;s how you say it. A business with a defined brand voice sounds recognizable across every touchpoint. One without a defined voice sounds like whoever wrote the copy that day.",
  },
  {
    q: "Why does brand voice matter for an Etsy shop?",
    a: "Because buyers buy from people, not entities. An Etsy shop with a distinct voice feels like a real person made and cares about what they&rsquo;re selling. That emotional resonance is a direct driver of trust, repeat purchases, and word-of-mouth. Generic copy — which is what you get without a defined voice — reads as interchangeable.",
  },
  {
    q: "How do I figure out my brand voice?",
    a: "Start with three questions: (1) How would your best customer describe your shop to a friend? (2) What words would you never use in your copy? (3) If your brand were a person at a dinner party, how would they talk? The answers give you a starting personality. Then look at your best-received copy — the listings, captions, or messages that got the most engagement — and identify what they have in common.",
  },
  {
    q: "How do I keep my brand voice consistent when I&rsquo;m writing different types of content?",
    a: "Write a one-page brand voice guide with 3-5 voice attributes and a &ldquo;sounds like / doesn&rsquo;t sound like&rdquo; example for each. Before publishing any copy, ask: does this sound like my brand? Read it out loud — if it sounds stiff or generic, it probably needs a voice edit.",
  },
  {
    q: "Can I have a warm brand voice and still be professional?",
    a: "Absolutely — and for Etsy shops, this combination is often the strongest. Warm but specific. Friendly but not flippant. Direct without being cold. The goal is sounding like an expert who genuinely cares about the person they&rsquo;re talking to — not like a corporate template and not like an over-caffeinated Instagram post.",
  },
];

export default function BrandVoiceSmallBusinessPost() {
  return (
    <>
      <Nav />
      <main style={{ background: "var(--warm-white)" }}>

        <section style={{ paddingTop: "100px", paddingBottom: "0", padding: "100px 40px 0" }}>
          <div style={{ maxWidth: "740px", margin: "0 auto" }}>
            <div style={{ display: "flex", gap: "12px", alignItems: "center", marginBottom: "24px", flexWrap: "wrap" }}>
              <span style={{ fontSize: "12px", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 600, color: "var(--cobalt)", background: "rgba(44,82,130,0.1)", padding: "4px 12px", borderRadius: "12px" }}>Brand Strategy</span>
              <span style={{ fontSize: "13px", color: "var(--horizon)", fontFamily: "Inter, system-ui, sans-serif" }}>11 min read · April 2026</span>
            </div>
            <h1 style={{ fontSize: "clamp(36px, 5vw, 56px)", lineHeight: 1.1, marginBottom: "24px" }}>
              What Is Brand Voice? (And How to Build One That Sounds Like You)
            </h1>
            <p style={{ fontSize: "11px", fontFamily: "Inter, system-ui, sans-serif", color: "var(--horizon)", marginBottom: "8px", letterSpacing: "0.05em" }}>
              By <a href="/about" style={{ color: "var(--cobalt)" }}>the Claro team</a>
            </p>
            <p style={{ fontSize: "20px", color: "var(--ink)", lineHeight: 1.7, marginTop: "32px", marginBottom: "0" }}>
              Read two Etsy listings in the same category and you can usually tell which one was written by a person who cares and which one was generated by a template. The difference isn&rsquo;t talent or budget. It&rsquo;s voice. Brand voice is what makes your copy sound like a human wrote it — specifically, like the human behind your shop.
            </p>
          </div>
        </section>

        <article style={{ padding: "48px 40px 96px", maxWidth: "740px", margin: "0 auto" }}>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "24px" }}>
            Without a defined brand voice, every piece of copy you write starts from scratch. The tone of your listing might not match the tone of your Instagram caption, which might not match the tone of your message to a buyer. The inconsistency erodes trust without you realizing it — because buyers experience your brand across multiple touchpoints, and when it doesn&rsquo;t cohere, it doesn&rsquo;t feel real.
          </p>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "48px" }}>
            Here&rsquo;s how to define your brand voice and actually use it.
          </p>

          <h2 style={{ fontSize: "32px", marginBottom: "20px", marginTop: "64px" }}>What brand voice is (and what it isn&rsquo;t)</h2>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "24px" }}>
            Brand voice is not a style guide. A style guide tells you whether to use Oxford commas. Brand voice tells you whether your copy sounds warm and direct or playful and self-deprecating.
          </p>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "24px" }}>
            Brand voice is also not the same as brand tone. Tone changes based on context — your tone in a marketing email is different from your tone when responding to a complaint. Voice stays constant. Voice is your personality. Tone is your mood.
          </p>

          <div style={{ background: "var(--ice)", border: "1px solid var(--sky)", borderRadius: "12px", padding: "28px 32px", margin: "32px 0" }}>
            <p style={{ fontSize: "15px", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 600, color: "var(--cobalt)", marginBottom: "12px" }}>Brand voice in practice:</p>
            <ul style={{ margin: 0, padding: "0 0 0 20px", display: "flex", flexDirection: "column", gap: "8px" }}>
              {[
                "Same personality, every touchpoint — listing, caption, email, message",
                "Recognizable even without seeing your logo or name",
                "Reflects who is behind the brand — specific, not generic",
                "Consistent regardless of who&rsquo;s writing (you on Monday vs. you at midnight)",
              ].map((item, i) => (
                <li key={i} style={{ fontSize: "16px", color: "var(--ink)", lineHeight: 1.6 }} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
            </ul>
          </div>

          <h2 style={{ fontSize: "32px", marginBottom: "20px", marginTop: "64px" }}>Step 1: Identify your voice attributes</h2>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "24px" }}>
            Voice attributes are adjectives that describe your brand&rsquo;s personality. Choose 3-5. They need to be specific enough to actually guide writing decisions.
          </p>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "16px", margin: "24px 0 32px" }}>
            {[
              { weak: "Professional", strong: "Direct" },
              { weak: "Friendly", strong: "Warm but specific" },
              { weak: "Authentic", strong: "Unfiltered-honest" },
              { weak: "Premium", strong: "Quietly confident" },
              { weak: "Fun", strong: "Dry-witted" },
            ].map((pair, i) => (
              <div key={i} style={{ background: "var(--ice)", borderRadius: "10px", padding: "20px" }}>
                <p style={{ fontSize: "13px", color: "#e57373", fontFamily: "Inter, system-ui, sans-serif", marginBottom: "6px" }}>✗ Too vague: &ldquo;{pair.weak}&rdquo;</p>
                <p style={{ fontSize: "14px", color: "var(--midnight)", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 600 }}>✓ Better: &ldquo;{pair.strong}&rdquo;</p>
              </div>
            ))}
          </div>

          <h2 style={{ fontSize: "32px", marginBottom: "20px", marginTop: "64px" }}>Step 2: Write the &ldquo;sounds like / doesn&rsquo;t sound like&rdquo; examples</h2>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "24px" }}>
            For each voice attribute, write one example of copy that embodies it and one that doesn&rsquo;t. This is the most useful part of a brand voice guide — it makes the abstract concrete.
          </p>

          {[
            {
              attribute: "Direct",
              sounds: "\"Ships in 48 hours. Arrives before the weekend.\"",
              doesnt: "\"We work hard to fulfill orders in a timely manner and appreciate your patience.\"",
            },
            {
              attribute: "Warm but specific",
              sounds: "\"Every candle is poured to order — we don&rsquo;t batch and warehouse because the scent is better fresh.\"",
              doesnt: "\"Our candles are made with love and care for our amazing customers!\"",
            },
            {
              attribute: "Quietly confident",
              sounds: "\"Non-toxic soy wax, clean fragrance. If you want something that smells like a chemical reaction, this isn&rsquo;t for you.\"",
              doesnt: "\"We believe we make the best candles on Etsy, and we hope you agree!\"",
            },
          ].map((ex, i) => (
            <div key={i} style={{ marginBottom: "36px" }}>
              <h4 style={{ fontSize: "18px", marginBottom: "16px", color: "var(--midnight)" }}>Attribute: {ex.attribute}</h4>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "16px" }}>
                <div style={{ background: "var(--ice)", borderRadius: "10px", padding: "20px", borderTop: "3px solid #c0392b" }}>
                  <p style={{ fontSize: "11px", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 700, color: "#e57373", marginBottom: "10px" }}>DOESN&rsquo;T SOUND LIKE</p>
                  <p style={{ fontSize: "15px", color: "var(--ink)", lineHeight: 1.6, fontStyle: "italic" }}>{ex.doesnt}</p>
                </div>
                <div style={{ background: "var(--cobalt)", borderRadius: "10px", padding: "20px", borderTop: "3px solid var(--gold)" }}>
                  <p style={{ fontSize: "11px", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 700, color: "var(--gold)", marginBottom: "10px" }}>SOUNDS LIKE</p>
                  <p style={{ fontSize: "15px", color: "var(--warm-white)", lineHeight: 1.6, fontStyle: "italic" }} dangerouslySetInnerHTML={{ __html: ex.sounds }} />
                </div>
              </div>
            </div>
          ))}

          <h2 style={{ fontSize: "32px", marginBottom: "20px", marginTop: "64px" }}>Step 3: Apply consistently across every touchpoint</h2>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "24px" }}>
            Your brand voice guide is only useful if you use it. Every time you write a new listing, caption, or email — check it against your voice attributes. Ask: does this sound like us? If not, what needs to change?
          </p>

          <p style={{ fontSize: "17px", color: "var(--ink)", lineHeight: 1.8, marginBottom: "48px" }}>
            The most common failure mode: voice is consistent in listings but completely different in social captions, which are different again in customer messages. Buyers who encounter all three touchpoints get a fragmented brand experience. The solution is simple: keep your voice guide visible when you write.
          </p>

          <div style={{ background: "var(--midnight)", borderRadius: "16px", padding: "40px", margin: "64px 0" }}>
            <p style={{ fontSize: "11px", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 600, color: "var(--horizon)", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "16px" }}>Know who you&rsquo;re talking to first</p>
            <h3 style={{ fontSize: "26px", color: "var(--warm-white)", marginBottom: "16px" }}>Brand voice is how you talk to your buyer. Know your buyer first.</h3>
            <p style={{ fontSize: "16px", color: "var(--sky)", lineHeight: 1.7, marginBottom: "24px" }}>
              Claro identifies your buyer&rsquo;s vocabulary and values — the raw material for a brand voice that resonates. See <a href="/pricing" style={{ color: "var(--gold)" }}>pricing</a>.
            </p>
            <a href="/#get-started" style={{ display: "inline-block", padding: "13px 24px", background: "var(--gold)", color: "var(--midnight)", borderRadius: "8px", fontSize: "15px", fontFamily: "Inter, system-ui, sans-serif", fontWeight: 700, textDecoration: "none" }}>
              Get your free buyer report →
            </a>
          </div>

          <h2 style={{ fontSize: "32px", marginBottom: "32px", marginTop: "64px" }}>Frequently asked questions</h2>
          <div style={{ display: "flex", flexDirection: "column" }}>
            {faqs.map((faq, i) => (
              <div key={i} style={{ borderTop: "1px solid var(--sky)", padding: "24px 0" }}>
                <h3 style={{ fontSize: "20px", marginBottom: "12px", color: "var(--midnight)" }}>{faq.q}</h3>
                <p style={{ fontSize: "16px", color: "var(--ink)", lineHeight: 1.7 }} dangerouslySetInnerHTML={{ __html: faq.a }} />
              </div>
            ))}
            <div style={{ borderTop: "1px solid var(--sky)" }} />
          </div>

          <h2 style={{ fontSize: "28px", marginBottom: "24px", marginTop: "64px" }}>Related reading</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
            {[
              { title: "How to Build a Brand Strategy for Your Small Business", href: "/blog/brand-strategy-small-business", label: "Brand Strategy" },
              { title: "The Solopreneur Brand Guide: How to Sound Like a Real Brand", href: "/blog/solopreneur-brand-guide", label: "Brand Strategy" },
              { title: "How to Write a Positioning Statement for Your Small Business", href: "/blog/positioning-statement-small-business", label: "Brand Strategy" },
            ].map((link) => (
              <a key={link.href} href={link.href} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", background: "var(--ice)", border: "1px solid var(--sky)", borderRadius: "12px", padding: "20px 24px", textDecoration: "none" }}>
                <span style={{ fontSize: "17px", color: "var(--midnight)", fontFamily: "'DM Serif Display', Georgia, serif" }}>{link.title}</span>
                <span style={{ fontSize: "13px", color: "var(--cobalt)", fontFamily: "Inter, system-ui, sans-serif" }}>{link.label} →</span>
              </a>
            ))}
          </div>

        </article>

        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "What Is Brand Voice? (And How to Build One That Sounds Like You)", author: { "@type": "Organization", name: "Claro" }, publisher: { "@type": "Organization", name: "Claro", url: "https://meetclaro.ai" }, datePublished: "2026-04-15", description: "Brand voice is what makes your copy sound like a person instead of a template. Here's how to define yours — and apply it consistently across your Etsy shop." }) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.q, acceptedAnswer: { "@type": "Answer", text: faq.a } })) }) }} />

      </main>
      <Footer />
    </>
  );
}
